### PR TITLE
 Factor out NIF HAL and add tests

### PR DESCRIPTION
**Pull request by fhunleth**
NOTE: This is untested, but it's a big change and I'm getting close to how I want it so I wanted to share.

---
This refactors the GPIO code to support pluggable hardware abstraction
layers (HALs) like Circuits.I2C and Circuits.SPI. Currently the options
are sysfs and a stub HAL suitable for testing on non-Linux platforms.

The second change is to pull out the unsafe and Raspberry Pi-specific
code for configuring pull ups and pull downs on GPIOs into a companion
helper app. This app runs in its own process to avoid any risk to
crashing the Erlang VM.

### CODE REVIEW

**Comment by fhunleth** [comment]
I take it back. I don't feel good about how the gpio_helper gets called. 

Two thoughts:

1. Change that part to be a really simple port process, supervise it, and send messages to it. 
2. Since this is only for the pull up/pull down code, it feels like a lot of work. I'm not sure it's worth it unless other platforms require similar things like mmap'ing /dev/mem to set pin pull modes. I think that I could be comfortable if we only supported /dev/gpio_mem.

**Comment by mattludwigs** [comment]
I like changing that to a port process. I agree with your thoughts on the second point as well.

**Comment by fhunleth** [comment]
Update: I've rebased the commits and added a few unit tests. The "stub" hardware abstraction layer connects pairs of GPIOs together and enabled quite a few tests - including interrupt ones.

**Comment by fhunleth** [comment]
I've done some light testing on real hardware. I'm thinking we should review this before adding I add too much more since it's getting a little large. If it's hard to review, I'll help walk through the changes or break out some of the easy commits to separate PRs.

**Comment by mattludwigs** [comment]
Things are looking good to me thus far. Probably will take a look at this on real hardware in the next few days, and circle back around to reviewing as are working on it. :rocket:

**Comment by fhunleth** [comment]
@mattludwigs and @mdsebald - I'm going to go ahead and merge this since I need to get this into hex.pm for use on other projects. Please bug me, file issues, or PR if you dislike anything that I did or if you find any mistakes.

**Pull request merged**
